In [76]:
import itertools
import numpy as np
import pandas as pd
from tabulate import tabulate
import random
from sklearn.metrics import euclidean_distances
# Initialize toy data
# 1 start point (0), 4 pick locations (1,2,3,4)

D = np.array([[0,13,11,17,11], [13,0,8,18,14], [11,8,0,11,6],[17,18,11,0,10], [11,14,6,10,0]])
D

# locations = [(5,0),(2,5),(4,5),(6,5),(8,5)]
# D = euclidean_distances(locations)*100 
# np.fill_diagonal(D, 999)
# D

array([[ 0, 13, 11, 17, 11],
       [13,  0,  8, 18, 14],
       [11,  8,  0, 11,  6],
       [17, 18, 11,  0, 10],
       [11, 14,  6, 10,  0]])

In [6]:
%%capture
from tqdm import tqdm_notebook as tqdm
tqdm().pandas()

In [77]:
# Generate set of actions and set of pick-nodes 
n=5 #Vincent heb ik zelf gemaakt....

Actions = set(range(n))
Nodes = Actions.copy()
Nodes.remove(0)
# Generate all possbile states
states = []
for j in range(n):
    if j > 0:
        subset = Nodes.copy()
    if j == 0:
        subset = Actions.copy()
    subset.remove(j)
    for i in range(len(subset)+1):
        a = list(itertools.combinations(subset, i)) 
        for k in range(len(a)):
            states.append((j,a[k]))
states

[(0, ()),
 (0, (1,)),
 (0, (2,)),
 (0, (3,)),
 (0, (4,)),
 (0, (1, 2)),
 (0, (1, 3)),
 (0, (1, 4)),
 (0, (2, 3)),
 (0, (2, 4)),
 (0, (3, 4)),
 (0, (1, 2, 3)),
 (0, (1, 2, 4)),
 (0, (1, 3, 4)),
 (0, (2, 3, 4)),
 (0, (1, 2, 3, 4)),
 (1, ()),
 (1, (2,)),
 (1, (3,)),
 (1, (4,)),
 (1, (2, 3)),
 (1, (2, 4)),
 (1, (3, 4)),
 (1, (2, 3, 4)),
 (2, ()),
 (2, (1,)),
 (2, (3,)),
 (2, (4,)),
 (2, (1, 3)),
 (2, (1, 4)),
 (2, (3, 4)),
 (2, (1, 3, 4)),
 (3, ()),
 (3, (1,)),
 (3, (2,)),
 (3, (4,)),
 (3, (1, 2)),
 (3, (1, 4)),
 (3, (2, 4)),
 (3, (1, 2, 4)),
 (4, ()),
 (4, (1,)),
 (4, (2,)),
 (4, (3,)),
 (4, (1, 2)),
 (4, (1, 3)),
 (4, (2, 3)),
 (4, (1, 2, 3))]

In [84]:
# Define the state space transition matrix 
Transition = np.zeros([len(states), n]) 
Transition = Transition.astype(int)

for i in range(len(states)):
    for j in range(n):
        new_set = set(states[i][1]) 
#         print(new_set)
        new_set.discard(j)
        new_set = tuple(new_set)
#         print(new_set)
        state = (j, new_set)
        print(state)
        Transition[i, j] = states.index(state)

Transition

(0, ())
(1, ())
(2, ())
(3, ())
(4, ())
(0, (1,))
(1, ())
(2, (1,))
(3, (1,))
(4, (1,))
(0, (2,))
(1, (2,))
(2, ())
(3, (2,))
(4, (2,))
(0, (3,))
(1, (3,))
(2, (3,))
(3, ())
(4, (3,))
(0, (4,))
(1, (4,))
(2, (4,))
(3, (4,))
(4, ())
(0, (1, 2))
(1, (2,))
(2, (1,))
(3, (1, 2))
(4, (1, 2))
(0, (1, 3))
(1, (3,))
(2, (1, 3))
(3, (1,))
(4, (1, 3))
(0, (1, 4))
(1, (4,))
(2, (1, 4))
(3, (1, 4))
(4, (1,))
(0, (2, 3))
(1, (2, 3))
(2, (3,))
(3, (2,))
(4, (2, 3))
(0, (2, 4))
(1, (2, 4))
(2, (4,))
(3, (2, 4))
(4, (2,))
(0, (3, 4))
(1, (3, 4))
(2, (3, 4))
(3, (4,))
(4, (3,))
(0, (1, 2, 3))
(1, (2, 3))
(2, (1, 3))
(3, (1, 2))
(4, (1, 2, 3))
(0, (1, 2, 4))
(1, (2, 4))
(2, (1, 4))
(3, (1, 2, 4))
(4, (1, 2))
(0, (1, 3, 4))
(1, (3, 4))
(2, (1, 3, 4))
(3, (1, 4))
(4, (1, 3))
(0, (2, 3, 4))
(1, (2, 3, 4))
(2, (3, 4))
(3, (2, 4))
(4, (2, 3))
(0, (1, 2, 3, 4))
(1, (2, 3, 4))
(2, (1, 3, 4))
(3, (1, 2, 4))
(4, (1, 2, 3))
(0, ())
(1, ())
(2, ())
(3, ())
(4, ())
(0, (2,))
(1, (2,))
(2, ())
(3, (2,))
(4, (2,))
(0, (3,))
(1, (3,))
(2, (3,))
(3, ())
(4, (3,))
(0, (4,))
(1, (4,))
(2, (4,))
(3, (4,))
(4, ())
(0, (2, 3))
(1, (2, 3))
(2, (3,))
(3, (2,))
(4, (2, 3))
(0, (2, 4))
(1, (2, 4))
(2, (4,))
(3, (2, 4))
(4, (2,))
(0, (3, 4))
(1, (3, 4))
(2, (3, 4))
(3, (4,))
(4, (3,))
(0, (2, 3, 4))
(1, (2, 3, 4))
(2, (3, 4))
(3, (2, 4))
(4, (2, 3))
(0, ())
(1, ())
(2, ())
(3, ())
(4, ())
(0, (1,))
(1, ())
(2, (1,))
(3, (1,))
(4, (1,))
(0, (3,))
(1, (3,))
(2, (3,))
(3, ())
(4, (3,))
(0, (4,))
(1, (4,))
(2, (4,))
(3, (4,))
(4, ())
(0, (1, 3))
(1, (3,))
(2, (1, 3))
(3, (1,))
(4, (1, 3))
(0, (1, 4))
(1, (4,))
(2, (1, 4))
(3, (1, 4))
(4, (1,))
(0, (3, 4))
(1, (3, 4))
(2, (3, 4))
(3, (4,))
(4, (3,))
(0, (1, 3, 4))
(1, (3, 4))
(2, (1, 3, 4))
(3, (1, 4))
(4, (1, 3))
(0, ())
(1, ())
(2, ())
(3, ())
(4, ())
(0, (1,))
(1, ())
(2, (1,))
(3, (1,))
(4, (1,))
(0, (2,))
(1, (2,))
(2, ())
(3, (2,))
(4, (2,))
(0, (4,))
(1, (4,))
(2, (4,))
(3, (4,))
(4, ())
(0, (1, 2))
(1, (2,))
(2, (1,))
(3, (1, 2))
(4, (1, 2))
(0, (1, 4))
(1, (4,))
(2, (1, 4))
(3, (1, 4))
(4, (1,))
(0, (2, 4))
(1, (2, 4))
(2, (4,))
(3, (2, 4))
(4, (2,))
(0, (1, 2, 4))
(1, (2, 4))
(2, (1, 4))
(3, (1, 2, 4))
(4, (1, 2))
(0, ())
(1, ())
(2, ())
(3, ())
(4, ())
(0, (1,))
(1, ())
(2, (1,))
(3, (1,))
(4, (1,))
(0, (2,))
(1, (2,))
(2, ())
(3, (2,))
(4, (2,))
(0, (3,))
(1, (3,))
(2, (3,))
(3, ())
(4, (3,))
(0, (1, 2))
(1, (2,))
(2, (1,))
(3, (1, 2))
(4, (1, 2))
(0, (1, 3))
(1, (3,))
(2, (1, 3))
(3, (1,))
(4, (1, 3))
(0, (2, 3))
(1, (2, 3))
(2, (3,))
(3, (2,))
(4, (2, 3))
(0, (1, 2, 3))
(1, (2, 3))
(2, (1, 3))
(3, (1, 2))
(4, (1, 2, 3))

array([[ 0, 16, 24, 32, 40],
       [ 1, 16, 25, 33, 41],
       [ 2, 17, 24, 34, 42],
       [ 3, 18, 26, 32, 43],
       [ 4, 19, 27, 35, 40],
       [ 5, 17, 25, 36, 44],
       [ 6, 18, 28, 33, 45],
       [ 7, 19, 29, 37, 41],
       [ 8, 20, 26, 34, 46],
       [ 9, 21, 27, 38, 42],
       [10, 22, 30, 35, 43],
       [11, 20, 28, 36, 47],
       [12, 21, 29, 39, 44],
       [13, 22, 31, 37, 45],
       [14, 23, 30, 38, 46],
       [15, 23, 31, 39, 47],
       [ 0, 16, 24, 32, 40],
       [ 2, 17, 24, 34, 42],
       [ 3, 18, 26, 32, 43],
       [ 4, 19, 27, 35, 40],
       [ 8, 20, 26, 34, 46],
       [ 9, 21, 27, 38, 42],
       [10, 22, 30, 35, 43],
       [14, 23, 30, 38, 46],
       [ 0, 16, 24, 32, 40],
       [ 1, 16, 25, 33, 41],
       [ 3, 18, 26, 32, 43],
       [ 4, 19, 27, 35, 40],
       [ 6, 18, 28, 33, 45],
       [ 7, 19, 29, 37, 41],
       [10, 22, 30, 35, 43],
       [13, 22, 31, 37, 45],
       [ 0, 16, 24, 32, 40],
       [ 1, 16, 25, 33, 41],
       [ 2, 17, 24, 34, 42],
       [ 4, 19, 27, 35, 40],
       [ 5, 17, 25, 36, 44],
       [ 7, 19, 29, 37, 41],
       [ 9, 21, 27, 38, 42],
       [12, 21, 29, 39, 44],
       [ 0, 16, 24, 32, 40],
       [ 1, 16, 25, 33, 41],
       [ 2, 17, 24, 34, 42],
       [ 3, 18, 26, 32, 43],
       [ 5, 17, 25, 36, 44],
       [ 6, 18, 28, 33, 45],
       [ 8, 20, 26, 34, 46],
       [11, 20, 28, 36, 47]])

In [79]:
# Now we want to define the reward matrix with negative distance
Reward = np.zeros([len(states), n])

for i in range(len(states)):
     for j in range(n):
            bonus = (i>0)*(len(states[i][1]) == 0 and j == 0) 
            Reward[i, j] = -D[states[i][0], j] + bonus*100
Reward

array([[  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [  0., -13., -11., -17., -11.],
       [ 87.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [-13.,   0.,  -8., -18., -14.],
       [ 89.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [-11.,  -8.,   0., -11.,  -6.],
       [ 83., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [-17., -18., -11.,   0., -10.],
       [ 89., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.],
       [-11., -14.,  -6., -10.,   0.]])

In [80]:
# ------------------- *** Q - Learning *** ----------------------------------- 
Q_table = np.ones([len(states), n])*1000

# Hyperparameters 
alpha = 0.2
gamma = 0.9 
epsilon = 0.3

# The algorithm

for i in tqdm(range(4000)):
    begin_state = (0, tuple(Nodes)) 
    state = states.index(begin_state) 
    done = False

    while not done:
        if random.uniform(0, 1) < epsilon:
            action = random.randrange(n) # Explore action space 
        else:
            action = np.argmax(Q_table[state]) # Exploit learned values

        next_state = Transition[state, action] 
        reward = Reward[state, action]

        if state == states.index((0, ())): 
            done = True

        old_value = Q_table[state, action] 

        next_max = np.max(Q_table[next_state])

        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max) 
        Q_table[state, action] = new_value

        state = next_state

q_df = pd.DataFrame(Q_table) 
q_df.index = states
q_df

HBox(children=(IntProgress(value=0, max=40000), HTML(value='')))

                            0           1           2           3           4
(0, ())            327.315789  359.884211  363.684211  352.284211  363.684211
(0, (1,))          323.895789  359.884211  317.395789  302.395789  311.995789
(0, (2,))          333.563242  322.170185  363.684211  316.398088  325.492181
(0, (3,))          317.086508  303.304925  311.555102  352.284211  313.361072
(0, (4,))          353.016268  329.552246  328.739979  330.071919  363.685369
(0, (1, 2))        285.656211  317.015789  317.395789  268.656211  279.156211
(0, (1, 3))        273.087407  303.155789  267.117432  302.432837  268.954147
(0, (1, 4))        312.068309  315.824551  299.637143  291.398110  316.029293
(0, (2, 3))        281.481958  270.584983  311.455789  310.335540  275.569642
(0, (2, 4))        313.337933  314.585373  323.155209  317.243360  323.002370
(0, (3, 4))        286.398659  270.063153  277.989093  311.545380  312.355789
(0, (1, 2, 3))     243.009189  270.010211  266.556211  268.656211  237.090589
(0, (1, 2, 4))     254.506863  278.869858  276.008788  241.460324  279.156211
(0, (1, 3, 4))     243.210796  266.424929  235.425507  265.131311  267.456211
(0, (2, 3, 4))     253.014162  239.840219  274.620214  273.068662  274.594579
(0, (1, 2, 3, 4))  213.381531  236.858189  234.210589  235.140589  237.090589
(1, ())            414.315789  372.884211  366.684211  351.284211  360.684211
(1, (2,))          314.315789  330.015789  366.684211  309.315789  317.815789
(1, (3,))          304.055993  316.159215  314.455824  351.284211  309.355790
(1, (4,))          320.346460  334.232439  333.425070  320.907419  360.684211
(1, (2, 3))        267.310211  283.010211  314.455789  309.315789  271.584211
(1, (2, 4))        289.400278  295.275888  323.815789  273.966293  318.095047
(1, (3, 4))        269.729486  279.550514  280.398964  310.215789  309.366333
(1, (2, 3, 4))     234.158199  249.858189  277.620211  271.634211  271.584211
(2, ())            416.315789  364.884211  374.684211  358.284211  368.684211
(2, (1,))          312.895789  364.884211  328.395789  308.395789  316.995789
(2, (3,))          306.055789  308.155789  322.455789  358.284211  317.355789
(2, (4,))          316.541635  317.184699  332.155504  319.688929  368.684211
(2, (1, 3))        261.840211  308.155789  277.556211  308.395789  272.456211
(2, (1, 4))        282.119664  316.635152  285.900751  272.562169  316.995789
(2, (3, 4))        270.120211  271.194211  285.620211  317.215789  317.355789
(2, (1, 3, 4))     229.710589  271.194211  245.210589  270.696211  272.456211
(3, ())            410.315789  354.884211  363.684211  369.284211  364.684211
(3, (1,))          306.895789  354.884211  317.395789  319.395789  312.995789
(3, (2,))          310.318368  312.016843  363.684211  327.315795  321.815906
(3, (4,))          310.561519  306.633500  320.835953  328.364213  364.684211
(3, (1, 2))        268.656211  312.015789  317.395789  285.656211  280.156211
(3, (1, 4))        274.545990  307.324863  275.460104  282.129969  312.995789
(3, (2, 4))        277.762291  280.796810  320.927401  292.189014  321.815789
(3, (1, 2, 4))     234.240589  273.434211  274.296211  252.140589  280.156211
(4, ())            416.315789  358.884211  368.684211  359.284211  374.684211
(4, (1,))          312.895789  358.884211  322.395789  309.395789  322.995789
(4, (2,))          316.542286  316.216415  368.684211  317.337418  331.873381
(4, (3,))          306.055789  302.155789  316.455789  359.284211  323.355789
(4, (1, 2))        274.656211  316.015789  322.395789  275.656211  290.156211
(4, (1, 3))        261.840211  302.155789  271.556211  309.395789  278.456211
(4, (2, 3))        269.548897  269.405000  316.457747  317.315789  286.065128
(4, (1, 2, 3))     232.009189  269.010211  271.556211  275.656211  248.090589

In [62]:
state
# states.index(begin_state) 
# np.argmax(Q_table[state])

24