In [1]:
import itertools
import numpy as np
import pandas as pd
from tabulate import tabulate
import random
from sklearn.metrics import euclidean_distances
# Initialize toy data
# 1 start point (0), 4 pick locations (1,2,3,4)

D = np.array([[0,13,11,17,11], [13,0,8,18,14], [11,8,0,11,6],[17,18,11,0,10], [11,14,6,10,0]])

# locations = [(5,0),(2,5),(4,5),(6,5),(8,5)] # D = euclidean_distances(locations)*100 np.fill_diagonal(D, 999)

In [2]:
# Generate set of actions and set of pick-nodes 
n=5 #Vincent heb ik zelf gemaakt....

Actions = set(range(n))
Nodes = Actions.copy()
Nodes.remove(0)
# Generate all possbile states
states = []
for j in range(n):
    if j > 0:
        subset = Nodes.copy()
    if j == 0:
        subset = Actions.copy()
    subset.remove(j)
    for i in range(len(subset)+1):
        a = list(itertools.combinations(subset, i)) 
        for k in range(len(a)):
            states.append((j,a[k]))

In [3]:
# Define the state space transition matrix 
Transition = np.zeros([len(states), n]) 
Transition = Transition.astype(int)

for i in range(len(states)):
    for j in range(n):
        new_set = set(states[i][1]) 
        new_set.discard(j)
        new_set = tuple(new_set)
        state = (j, new_set)
        Transition[i, j] = states.index(state)

In [4]:
# Now we want to define the reward matrix with negative distance
Reward = np.zeros([len(states), n])

for i in range(len(states)):
     for j in range(n):
            bonus = (i>0)*(len(states[i][1]) == 0 and j == 0) 
            Reward[i, j] = -D[states[i][0], j] + bonus*100

In [5]:
# ------------------- *** Q - Learning *** ----------------------------------- 
Q_table = np.ones([len(states), n])*1000

# Hyperparameters 
alpha = 0.2
gamma = 0.9 
epsilon = 0.3

# The algorithm

for i in range(400000):
    begin_state = (0, tuple(Nodes)) 
    state = states.index(begin_state) 
    done = False

    while not done:
        if random.uniform(0, 1) < epsilon:
            action = random.randrange(n) # Explore action space 
        else:
            action = np.argmax(Q_table[state]) # Exploit learned values

        next_state = Transition[state, action] 
        reward = Reward[state, action]

        if state == states.index((0, ())): 
            done = True

        old_value = Q_table[state, action] 

        next_max = np.max(Q_table[next_state])

        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max) 
        Q_table[state, action] = new_value

        state = next_state

q_df = pd.DataFrame(Q_table) 
q_df.index = states
q_df

                            0           1           2           3           4
(0, ())            327.315789  359.884211  363.684211  352.284211  363.684211
(0, (1,))          323.895789  359.884211  317.395789  302.395789  311.995789
(0, (2,))          327.315789  317.015789  363.684211  310.315789  320.815789
(0, (3,))          317.055789  303.155789  311.455789  352.284211  312.355789
(0, (4,))          327.385507  311.852590  320.828796  311.277323  363.684211
(0, (1, 2))        285.656211  317.015789  317.395789  268.656211  279.156211
(0, (1, 3))        272.840211  303.155789  266.556211  302.395789  267.456211
(0, (1, 4))        281.858878  311.671092  276.402739  265.127451  311.995789
(0, (2, 3))        280.310211  270.010211  311.455789  310.315789  274.584211
(0, (2, 4))        294.562182  282.704312  320.815789  275.745400  320.815790
(0, (3, 4))        281.120211  266.194211  274.620211  311.215789  312.355789
(0, (1, 2, 3))     243.009189  270.010211  266.556211  268.656211  237.090589
(0, (1, 2, 4))     251.240589  278.434211  274.296211  235.140590  279.156211
(0, (1, 3, 4))     240.710589  266.194211  234.210590  264.696211  267.456211
(0, (2, 3, 4))     247.158189  236.858189  274.620211  272.634211  274.584211
(0, (1, 2, 3, 4))  213.381531  236.858189  234.210589  235.140589  237.090589
(1, ())            414.315789  372.884211  366.684211  351.284211  360.684211
(1, (2,))          314.315789  330.015789  366.684211  309.315789  317.815789
(1, (3,))          304.055789  316.155789  314.455789  351.284211  309.355789
(1, (4,))          314.316818  324.616672  323.815837  310.216360  360.684211
(1, (2, 3))        267.310211  283.010211  314.455789  309.315789  271.584211
(1, (2, 4))        275.734211  291.434211  323.815789  271.634211  317.815789
(1, (3, 4))        268.120211  279.194211  277.620211  310.215789  309.355789
(1, (2, 3, 4))     234.158189  249.858189  277.620211  271.634211  271.584211
(2, ())            416.315789  364.884211  374.684211  358.284211  368.684211
(2, (1,))          312.895789  364.884211  328.395789  308.395789  316.995789
(2, (3,))          306.055789  308.155789  322.455789  358.284211  317.355789
(2, (4,))          316.315789  316.615789  331.815789  317.215789  368.684211
(2, (1, 3))        261.840211  308.155789  277.556211  308.395789  272.456211
(2, (1, 4))        269.796211  316.615789  285.296211  270.696211  316.995789
(2, (3, 4))        270.120211  271.194211  285.620211  317.215789  317.355789
(2, (1, 3, 4))     229.710589  271.194211  245.210589  270.696211  272.456211
(3, ())            410.315789  354.884211  363.684211  369.284211  364.684211
(3, (1,))          306.895789  354.884211  317.395789  319.395789  312.995789
(3, (2,))          310.315789  312.015789  363.684211  327.315789  321.815789
(3, (4,))          310.315789  306.615789  320.815789  328.215789  364.684211
(3, (1, 2))        268.656211  312.015789  317.395789  285.656211  280.156211
(3, (1, 4))        263.796211  306.615789  274.296211  281.696211  312.995789
(3, (2, 4))        271.734211  273.434211  320.815789  289.634211  321.815789
(3, (1, 2, 4))     234.240589  273.434211  274.296211  252.140589  280.156211
(4, ())            416.315789  358.884211  368.684211  359.284211  374.684211
(4, (1,))          312.895789  358.884211  322.395789  309.395789  322.995789
(4, (2,))          316.315789  316.015789  368.684211  317.315789  331.815789
(4, (3,))          306.055789  302.155789  316.455789  359.284211  323.355789
(4, (1, 2))        274.656211  316.015789  322.395789  275.656211  290.156211
(4, (1, 3))        261.840211  302.155789  271.556211  309.395789  278.456211
(4, (2, 3))        269.310211  269.010211  316.455789  317.315789  285.584211
(4, (1, 2, 3))     232.009189  269.010211  271.556211  275.656211  248.090589