In [1]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
import os
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_excel('/Users/vpavandijk/LEARNING/Ironhack/End_project/data_received_of_KN/data_25_wk_dump.xlsx')

In [3]:
data.head()

,princip,I_O,soort,ord_nr,art_cde,art_sub_nr,partij_nr,aant_adm_verz,aant_adm_blk,aant_adm_vrij,mut_mom_datum,mut_mom_tijd,mut_stat,tht_dat,rit_nr,pal_nr,car_nr,user_id,verpl_doc_nr,relatie_cde,mut_oorz,mut_rek_cde,sectie_cde,gang_nr,kolom_nr,laag_nr,pos_nr,ext_car_cde,Zoeksleutel,ext_ref_cde
0,6020,C,B,NaN,11087891.0,1,L9092K101,0,420,0,06-01-2020,00:01:31,2,02/02/20,0,6857652,13891134,NaN,0,NaN,NaN,NaN,L2P,224,45,1,2,3.871425e+17,06-01-2020-00:01:31-011087891-0--224.45.1-2,NaN
1,6020,C,B,18668.0,11034600.0,3,GX401518051,0,-21,0,06-01-2020,07:54:48,2,19/12/19,0,7078671,14456732,hri,0,NaN,30.0,3.0,L2A,233,33,3,3,3.871425e+17,06-01-2020-07:54:48-011034600-0-hri-233.33.3-3,NaN
2,6020,C,B,18668.0,11034600.0,3,GX401518051,0,-21,0,06-01-2020,13:40:39,2,19/12/19,0,7078671,14456732,hri,0,NaN,30.0,3.0,L2A,233,33,3,3,3.871425e+17,06-01-2020-13:40:39-011034600-0-hri-233.33.3-3,NaN
3,6020,C,B,18668.0,11034600.0,3,GX401518051,0,0,0,06-01-2020,07:59:48,2,19/12/19,0,7078671,14456732,NaN,0,NaN,NaN,NaN,L2A,233,33,3,3,3.871425e+17,06-01-2020-07:59:48-011034600-0--233.33.3-3,NaN
4,6020,C,B,18668.0,11034600.0,3,GX401518051,0,0,0,06-01-2020,13:45:14,2,19/12/19,0,7078671,14456732,NaN,0,NaN,NaN,NaN,L2A,233,33,3,3,3.871425e+17,06-01-2020-13:45:14-011034600-0--233.33.3-3,NaN

In [4]:
data_picking = data[(data['I_O'] == 'O') & (data['soort'] == 'P')]
data_picking

,princip,I_O,soort,ord_nr,art_cde,art_sub_nr,partij_nr,aant_adm_verz,aant_adm_blk,aant_adm_vrij,mut_mom_datum,mut_mom_tijd,mut_stat,tht_dat,rit_nr,pal_nr,car_nr,user_id,verpl_doc_nr,relatie_cde,mut_oorz,mut_rek_cde,sectie_cde,gang_nr,kolom_nr,laag_nr,pos_nr,ext_car_cde,Zoeksleutel,ext_ref_cde
1089,6020,O,P,107026770.0,11001307.0,1,FH220191224,1,0,0,06-01-2020,16:36:23,0,?,317565,7137669,14617917,2100,22900216,112706,NaN,NaN,L2P,218,49,1,1,3.871425e+17,06-01-2020-16:36:23-011001307-0-2100-218.49.1-1,13350000
1090,6020,O,P,107026770.0,11001308.0,1,FH220191221,1,0,0,06-01-2020,17:05:42,0,?,317565,7155680,14617917,2100,22900216,112706,NaN,NaN,L2P,222,50,1,3,3.871425e+17,06-01-2020-17:05:42-011001308-0-2100-222.50.1-3,13350000
1091,6020,O,P,107026770.0,11002052.0,1,1213148,32,0,0,06-01-2020,16:50:20,0,24/08/20,317565,7135229,14617917,2100,22900216,112706,NaN,NaN,L2P,218,50,1,3,3.871425e+17,06-01-2020-16:50:20-011002052-0-2100-218.50.1-3,13350000
1092,6020,O,P,107026770.0,11021282.0,1,150974,3,0,0,06-01-2020,16:54:32,0,?,317565,7157104,14617917,2100,22900216,112706,NaN,NaN,l2p,220,46,1,3,3.871425e+17,06-01-2020-16:54:32-011021282-0-2100-220.46.1-3,13350000
1093,6020,O,P,107026770.0,11024583.0,2,190337-001,25,0,0,06-01-2020,17:38:56,0,?,317565,7146376,14617917,2100,22900216,112706,NaN,NaN,L2P,225,46,1,1,3.871425e+17,06-01-2020-17:38:56-011024583-0-2100-225.46.1-1,13350000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649316,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,20:55:22,0,31/08/20,342563,7394982,15558841,2080,24447292,619804,NaN,NaN,l2p,216,41,1,3,3.871425e+17,30-06-2020-20:55:22-011105997-0-2080-216.41.1-3,13784413
649317,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,20:56:09,0,31/08/20,342563,7394980,15558844,8888,24447295,619804,NaN,NaN,l2p,216,45,1,1,3.871425e+17,30-06-2020-20:56:09-011105997-0-8888-216.45.1-1,13784413
649318,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,21:01:04,0,31/08/20,342563,7394985,15558845,8888,24447296,619804,NaN,NaN,l2p,216,46,1,4,3.871425e+17,30-06-2020-21:01:04-011105997-0-8888-216.46.1-4,13784413
649319,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,21:01:15,0,31/08/20,342563,7395000,15558847,2068,24447298,619804,NaN,NaN,l2p,216,46,1,3,3.871425e+17,30-06-2020-21:01:15-011105997-0-2068-216.46.1-3,13784413
649320,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,21:07:28,0,31/08/20,342563,7394983,15558846,2068,24447297,619804,NaN,NaN,l2p,216,46,1,1,3.871425e+17,30-06-2020-21:07:28-011105997-0-2068-216.46.1-1,13784413

In [5]:
data_picking.dtypes

princip            int64
I_O               object
soort             object
ord_nr           float64
art_cde          float64
art_sub_nr         int64
partij_nr         object
aant_adm_verz      int64
aant_adm_blk       int64
aant_adm_vrij      int64
mut_mom_datum     object
mut_mom_tijd      object
mut_stat           int64
tht_dat           object
rit_nr             int64
pal_nr             int64
car_nr             int64
user_id           object
verpl_doc_nr       int64
relatie_cde       object
mut_oorz         float64
mut_rek_cde      float64
sectie_cde        object
gang_nr           object
kolom_nr          object
laag_nr           object
pos_nr            object
ext_car_cde      float64
Zoeksleutel       object
ext_ref_cde       object
dtype: object

In [11]:
data_picking.isnull().sum()

princip               0
I_O                   0
soort                 0
ord_nr                0
art_cde               0
art_sub_nr            0
partij_nr             6
aant_adm_verz         0
aant_adm_blk          0
aant_adm_vrij         0
mut_mom_datum         0
mut_mom_tijd          0
mut_stat              0
tht_dat               0
rit_nr                0
pal_nr                0
car_nr                0
user_id               0
verpl_doc_nr          0
relatie_cde           0
mut_oorz         266500
mut_rek_cde      266500
sectie_cde            0
gang_nr               0
kolom_nr              0
laag_nr               0
pos_nr                0
ext_car_cde           0
Zoeksleutel           0
ext_ref_cde           0
dtype: int64

In [13]:
nr_pallets_out = data_picking['ext_car_cde'].unique()
len(nr_pallets_out)

7071

In [7]:
# data_picking['pos_nr'].value_counts()

In [8]:
# data_picking['ext_car_cde'] = data_picking['ext_car_cde'].astype(int)
# data_picking['ord_nr'] = data_picking['ord_nr'].astype(int)
# data_picking['art_cde'] = data_picking['art_cde'].astype(int)
# data_picking['gang_nr'] = data_picking['gang_nr'].astype(int)
# data_picking['kolom_nr'] = data_picking['kolom_nr'].astype(int)
# data_picking['laag_nr'] = data_picking['laag_nr'].astype(int)
# data_picking['pos_nr'] = data_picking['pos_nr'].astype(int)

In [9]:
test = data_picking[data_picking['ext_car_cde'] == 387142544272259264]
test

,princip,I_O,soort,ord_nr,art_cde,art_sub_nr,partij_nr,aant_adm_verz,aant_adm_blk,aant_adm_vrij,mut_mom_datum,mut_mom_tijd,mut_stat,tht_dat,rit_nr,pal_nr,car_nr,user_id,verpl_doc_nr,relatie_cde,mut_oorz,mut_rek_cde,sectie_cde,gang_nr,kolom_nr,laag_nr,pos_nr,ext_car_cde,Zoeksleutel,ext_ref_cde
647756,6020,O,P,502985549.0,11093706.0,1,YRP382675J0212,224,0,0,30-06-2020,21:19:52,0,31/10/20,341184,7537508,15559189,2227,24447903,523796,NaN,NaN,L2P,222,50,1,3,3.871425e+17,30-06-2020-21:19:52-011093706-0-2227-222.50.1-3,13751076
647757,6020,O,P,502985549.0,11093706.0,1,YRP382675J0212,224,0,0,30-06-2020,21:23:47,0,31/10/20,341184,7537510,15559191,2068,24447905,523796,NaN,NaN,L2P,223,42,1,1,3.871425e+17,30-06-2020-21:23:47-011093706-0-2068-223.42.1-1,13751076
647758,6020,O,P,502985549.0,11093706.0,1,YRP382675J0212,448,0,0,30-06-2020,21:11:04,0,31/10/20,341184,7537509,15559190,2068,24447904,523796,NaN,NaN,L2P,223,33,1,3,3.871425e+17,30-06-2020-21:11:04-011093706-0-2068-223.33.1-3,13751076
647759,6020,O,P,502985549.0,11093706.0,1,YRP382675J0212,448,0,0,30-06-2020,21:11:36,0,31/10/20,341184,7537510,15559190,2068,24447904,523796,NaN,NaN,L2P,223,42,1,1,3.871425e+17,30-06-2020-21:11:36-011093706-0-2068-223.42.1-1,13751076
647760,6020,O,P,502985549.0,11093706.0,1,YRP382675J0212,672,0,0,30-06-2020,21:31:56,0,31/10/20,341184,7537509,15559189,2227,24447903,523796,NaN,NaN,L2P,223,33,1,3,3.871425e+17,30-06-2020-21:31:56-011093706-0-2227-223.33.1-3,13751076
647761,6020,O,P,502985549.0,11093706.0,1,YRP382675J0212,896,0,0,30-06-2020,21:18:38,0,31/10/20,341184,7537508,15559188,2227,24447902,523796,NaN,NaN,L2P,222,50,1,3,3.871425e+17,30-06-2020-21:18:38-011093706-0-2227-222.50.1-3,13751076
649150,6020,O,P,502991224.0,11001125.0,1,TW01117048672,48,0,0,30-06-2020,20:52:53,0,?,342565,4774114,15557659,6858,24445213,2681,NaN,NaN,L2P,228,45,1,3,3.871425e+17,30-06-2020-20:52:53-011001125-0-6858-228.45.1-3,13783087
649151,6020,O,P,502991224.0,11001125.0,3,TW01117048672,2,0,0,30-06-2020,20:51:59,0,?,342565,7074550,15557659,6858,24445213,2681,NaN,NaN,L2P,228,45,1,3,3.871425e+17,30-06-2020-20:51:59-011001125-0-6858-228.45.1-3,13783087
649152,6020,O,P,502991224.0,11005800.0,1,29102019,8,0,0,30-06-2020,20:46:53,0,?,342565,6985381,15557659,6858,24445213,2681,NaN,NaN,L2P,228,48,1,3,3.871425e+17,30-06-2020-20:46:53-011005800-0-6858-228.48.1-3,13783087
649153,6020,O,P,502991224.0,11005800.0,1,29102019,24,0,0,30-06-2020,20:45:47,0,?,342565,6985394,15557659,6858,24445213,2681,NaN,NaN,L2P,228,29,1,1,3.871425e+17,30-06-2020-20:45:47-011005800-0-6858-228.29.1-1,13783087
649162,6020,O,P,502991224.0,11005801.0,3,25072019,4,0,0,30-06-2020,20:58:10,0,?,342565,7546894,15557659,6858,24445213,2681,NaN,NaN,L2P,219,55,1,4,3.871425e+17,30-06-2020-20:58:10-011005801-0-6858-219.55.1-4,13783087
649167,6020,O,P,502991224.0,11011191.0,3,FH220200204,6,0,0,30-06-2020,20:49:11,0,?,342565,7257560,15557659,6858,24445213,2681,NaN,NaN,L2P,228,39,1,3,3.871425e+17,30-06-2020-20:49:11-011011191-0-6858-228.39.1-3,13783087
649180,6020,O,P,502991224.0,11041064.0,1,2002279,24,0,0,30-06-2020,20:49:39,0,?,342565,7315357,15557659,6858,24445213,2681,NaN,NaN,L2P,228,40,1,4,3.871425e+17,30-06-2020-20:49:39-011041064-0-6858-228.40.1-4,13783087
649182,6020,O,P,502991224.0,11041064.0,3,2002279,8,0,0,30-06-2020,20:59:30,0,?,342565,7547586,15557659,6858,24445213,2681,NaN,NaN,l2p,217,56,1,8,3.871425e+17,30-06-2020-20:59:30-011041064-0-6858-217.56.1-8,13783087
649184,6020,O,P,502991224.0,11041893.0,2,1030718108,18,0,0,30-06-2020,20:48:12,0,?,342565,7295746,15557659,6858,24445213,2681,NaN,NaN,L2P,228,39,1,1,3.871425e+17,30-06-2020-20:48:12-011041893-0-6858-228.39.1-1,13783087
649231,6020,O,P,502991224.0,11090645.0,3,5393562,4,0,0,30-06-2020,20:51:23,0,?,342565,7679344,15557659,6858,24445213,2681,NaN,NaN,L2P,228,43,1,1,3.871425e+17,30-06-2020-20:51:23-011090645-0-6858-228.43.1-1,13783087
649243,6020,O,P,502991224.0,11090646.0,3,FH220200128,60,0,0,30-06-2020,20:55:15,0,?,342565,7212944,15557659,6858,24445213,2681,NaN,NaN,L2P,227,55,1,2,3.871425e+17,30-06-2020-20:55:15-011090646-0-6858-227.55.1-2,13783087
649257,6020,O,P,502991224.0,11105912.0,3,FH220200622,4,0,0,30-06-2020,20:53:38,0,?,342565,7656347,15557659,6858,24445213,2681,NaN,NaN,L2P,228,47,1,1,3.871425e+17,30-06-2020-20:53:38-011105912-0-6858-228.47.1-1,13783087
649277,6020,O,P,502991224.0,11111860.0,3,FH220200225,2,0,0,30-06-2020,20:56:28,0,?,342565,7295827,15557659,6858,24445213,2681,NaN,NaN,L2P,226,57,1,1,3.871425e+17,30-06-2020-20:56:28-011111860-0-6858-226.57.1-1,13783087
649312,6020,O,P,502991717.0,11105997.0,1,36471,306,0,0,30-06-2020,20:51:45,0,31/08/20,342563,7394989,15558843,2017,24447294,619804,NaN,NaN,l2p,216,43,1,4,3.871425e+17,30-06-2020-20:51:45-011105997-0-2017-216.43.1-4,13784413
649313,6020,O,P,502991717.0,11105997.0,1,36471,336,0,0,30-06-2020,20:56:33,0,31/08/20,342563,7394995,15558843,2017,24447294,619804,NaN,NaN,l2p,216,47,1,4,3.871425e+17,30-06-2020-20:56:33-011105997-0-2017-216.47.1-4,13784413
649314,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,20:45:42,0,31/08/20,342563,7394981,15558840,2068,24447291,619804,NaN,NaN,l2p,216,41,1,1,3.871425e+17,30-06-2020-20:45:42-011105997-0-2068-216.41.1-1,13784413
649315,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,20:50:54,0,31/08/20,342563,7395005,15558842,2017,24447293,619804,NaN,NaN,l2p,216,42,1,1,3.871425e+17,30-06-2020-20:50:54-011105997-0-2017-216.42.1-1,13784413
649316,6020,O,P,502991717.0,11105997.0,1,36471,720,0,0,30-06-2020,20:55:22,0,31/08/20,342563,7394982,15558841,2080,24447292,619804,NaN,NaN,l2p,216,41,1,3,3.871425e+17,30-06-2020-20:55:22-011105997-0-2080-216.41.1-3,13784413

In [15]:
data_picking.groupby('ext_car_cde').count()

,princip,I_O,soort,ord_nr,art_cde,art_sub_nr,partij_nr,aant_adm_verz,aant_adm_blk,aant_adm_vrij,mut_mom_datum,mut_mom_tijd,mut_stat,tht_dat,rit_nr,pal_nr,car_nr,user_id,verpl_doc_nr,relatie_cde,mut_oorz,mut_rek_cde,sectie_cde,gang_nr,kolom_nr,laag_nr,pos_nr,Zoeksleutel,ext_ref_cde
ext_car_cde,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
3.871423e+17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
3.871425e+17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
3.871425e+17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
3.871425e+17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
3.871425e+17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3.871425e+17,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,0,0,9,9,9,9,9,9,9
3.871425e+17,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,0,0,12,12,12,12,12,12,12
3.871425e+17,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,0,0,7,7,7,7,7,7,7
3.871425e+17,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,0,0,24,24,24,24,24,24,24
3.871425e+17,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,0,0,93,93,93,93,93,93,93

In [18]:
data_picking.pivot(index = 'ext_car_cde', columns = 'princip')

ValueError: Index contains duplicate entries, cannot reshape